version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - run: |
          cp .vimrc ~/.vimrc
          git config --global user.name "Lev Lazinskiy"
          git config --global user.email lev@levlaz.org
      
